### ISSUE TITLE
JRE7/8 error on SSL certificates

### ISSUE THREAD

**Issue by DawidJanczak** [rodolpheche/wiremock-docker#36]
Hello,

I'm trying to use this image as a web proxy for our Selenium integration tests, but I can't get HTTPS proxying to work. I finally traced it down to something odd: visiting http://localhost:8080/__admin/certs/wiremock-ca.crt presents me with a page saying "HTTPS Browser Proxying, including CA certificate retrieval, requires wiremock-jre8". That error seems to be coming from https://github.com/tomakehurst/wiremock/blob/master/java7/src/main/java/com/github/tomakehurst/wiremock/admin/tasks/GetCaCertTask.java, but that's a version 7 build and this image clearly uses version 8. Not sure what's going on here so I figured I'd ask here. Oh and I'm using the `rodolpheche/wiremock:2.27.1-alpine` image.

**Comment by rodolpheche** [comment]
Hello,

Thanks for your report.

I remember that the Java 8 version doesn't run inside alpine container because of missing _Server ALPNProcessors_.
I start investigating on this issue

**Comment by rodolpheche** [comment]
Hi,

It's fixed.
Waiting the next release, you can use the [master](https://hub.docker.com/layers/rodolpheche/wiremock/master/images/sha256-6c35dd8787c651ef8065e426eb5e66c6fccb5e1467cc446831e1986ff17a3730?context=repo) version of the image.

The issue was caused by the particularity of the alpine image that is based on musl (in replacement of the glibc).
It needs to embed the libc6-compat dependency to work fine with jre8
