### ISSUE TITLE
Arguments for Wiremock

### ISSUE THREAD

**Issue by cultavix** [rodolpheche/wiremock-docker#6]
Hi,

I am trying to tie this together with another service, which I want to use to fetch some fake config data for testing.

However, I'm using `docker-compose` and I can't figure out how to use `--record-mappings --verbose` (or any other runtime argument)

I can see that you are running the actual `wiremock.jar` file here: https://github.com/rodolpheche/wiremock-docker/blob/master/Dockerfile#L32 (or maybe here: https://github.com/rodolpheche/wiremock-docker/blob/master/docker-entrypoint.sh#L7)

Would it be possible for you to add a new `ENV_VAR`, i.e. - `WIREMOCK_OPTS` to make this a bit more configurable and usable in `docker-compose` ?

I'd like to contribute, otherwise, I'll just have to do YET ANOTHER FORK :P

Thanks :)

**Comment by cultavix** [comment]
Nevermind, I've just realised I can just use `command:` here :) I'll close this!

**Comment by bkrahmer** [comment]
I think this feature would be nice to have and should be a one line change.  The alternative is to add 7 lines (of fragile code that can diverge from this published image) to my docker-compose file just to add one command-line argument

**Comment by mkeology** [comment]
Hello,
I am a regular user of this image and I am curious about your question ...

For me, one of the advantages of using this image, is that it allows users to customize the configuration for each container based on this image, using the given wiremock conventions, so that it bubbles up straight to the wiremock context using the innate docker ecosystem mechanisms ...

Example :: without using docker-compose, as stated in the readme, you can alternatively, easily add wiremock context parameters using docker run ...  

[readme] :: Start a Wiremock container with Wiremock arguments

Why don't you just use the  "command:" key/element in your docker-compose file to customize the configuration and contextualize your specific use of this image like any other image (Traefik labels, couchDb ENV vars) ?

Thanks for your insight....

**Comment by bkrahmer** [comment]
I agree that there is a lot of wiremock functionality you can get from using the image without changing the command-line.  However, when you want to further customize wiremock behavior, such as disabling the printed banner, you need to use command-line arguments.  Of course, I can and currently am overriding the command-line.  However, as I mentioned, this is fragile (if the command-line in the image changes, my setup will break), and requires what I would call internal implementation details.  By simply offering a way to add the command-line parameters populated from a single environment variable, the changes in my docker-compose file would be 2 added lines vs. 7+ lines.  Hopefully you see what I mean now.

**Comment by rodolpheche** [comment]
@bkrahmer,

Integrate a Docker environment variable to handle Wiremock arguments does not make sense since this image has been designed to use Docker commands for that.

You mentioned it's fragile because the command line in the image may change.
I don't understand what you mean... I guess you are confusing with the entrypoint.
This image has a default command line (handled by the entrypoint) that the user may override with his needs.

So, here is what you should do:

#### Initialize Wiremock arguments

```bash
export WIREMOCK_ARGS="--https-port 8443 \
--verbose"
```

#### Usage

##### With Docker

```bash
docker run rodolpheche/wiremock $WIREMOCK_ARGS
```

##### With Docker Compose/Swarm

```yml
command: $WIREMOCK_ARGS
```

**Comment by bkrahmer** [comment]
hi @rodolpheche, thanks for your comment.  I wasn't aware of the WIREMOCK_ARGS route.  You mention a bit about args on the main readme, but it wasn't clear in the context of using it with docker-compose.  I can verify that `command: ["--disable-banner", "true"]` does work correctly.  Thanks for your hard work
